services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: friendly-postgres-local
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "1177:5432"